default_settings: null
behaviors:
  CreatureAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 5000000
    time_horizon: 1000
    summary_freq: 20000

environment_parameters:
  roughness:
    curriculum:
      - name: Lesson0_FlatGround
        completion_criteria:
          measure: reward
          behavior: CreatureAgent
          signal_smoothing: true
          min_lesson_length: 50
          threshold: 80.0
        value: 0.0
      - name: Lesson1_GentleRoughness
        completion_criteria:
          measure: reward
          behavior: CreatureAgent
          signal_smoothing: true
          min_lesson_length: 50
          threshold: 140.0
        value: 0.25
      - name: Lesson2_ModerateRoughness
        completion_criteria:
          measure: reward
          behavior: CreatureAgent
          signal_smoothing: true
          min_lesson_length: 60
          threshold: 200.0
        value: 0.5
      - name: Lesson3_ExtremeRoughness
        value: 1.0
